BEGIN;

DO $$
DECLARE
  server_major_version integer := current_setting('server_version_num')::integer / 10000;
BEGIN
  IF server_major_version <> 16 THEN
    RAISE EXCEPTION 'FE-neo-app requires PostgreSQL 16; connected server major version is %', server_major_version;
  END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee_app;

COMMENT ON SCHEMA employee_app IS
  'Employee Database Lab schema for NEO DB PostgreSQL 16';

CREATE TABLE IF NOT EXISTS employee_app.schema_migrations (
  version varchar(50) PRIMARY KEY,
  description varchar(255) NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS employee_app.sites (
  site_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  address varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_app.salaries (
  salary_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salary_grade varchar(50) NOT NULL,
  basic_salary numeric(12, 2) NOT NULL,
  allowance numeric(12, 2) NOT NULL DEFAULT 0.00,
  CONSTRAINT salaries_basic_salary_nonnegative CHECK (basic_salary >= 0),
  CONSTRAINT salaries_allowance_nonnegative CHECK (allowance >= 0)
);

CREATE TABLE IF NOT EXISTS employee_app.seating (
  seating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id integer NOT NULL,
  floor_number varchar(20) NOT NULL,
  seat_code varchar(50) NOT NULL,
  CONSTRAINT seating_site_fk
    FOREIGN KEY (site_id) REFERENCES employee_app.sites(site_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS employee_app.employees (
  employee_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id integer NOT NULL,
  salary_id integer NOT NULL,
  seating_id integer NOT NULL,
  full_name varchar(120) NOT NULL,
  email varchar(120) NOT NULL UNIQUE,
  job_title varchar(100) NOT NULL,
  hired_date date NOT NULL,
  CONSTRAINT employees_site_fk
    FOREIGN KEY (site_id) REFERENCES employee_app.sites(site_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT employees_salary_fk
    FOREIGN KEY (salary_id) REFERENCES employee_app.salaries(salary_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT employees_seating_fk
    FOREIGN KEY (seating_id) REFERENCES employee_app.seating(seating_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS employee_app.employee_devices (
  employee_device_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL,
  site_id integer NOT NULL,
  device_type varchar(50) NOT NULL,
  device_brand varchar(50) NOT NULL,
  serial_number varchar(100) NOT NULL UNIQUE,
  assigned_date date NOT NULL,
  CONSTRAINT employee_devices_employee_fk
    FOREIGN KEY (employee_id) REFERENCES employee_app.employees(employee_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT employee_devices_site_fk
    FOREIGN KEY (site_id) REFERENCES employee_app.sites(site_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS seating_site_id_idx
  ON employee_app.seating(site_id);

CREATE INDEX IF NOT EXISTS employees_site_id_idx
  ON employee_app.employees(site_id);

CREATE INDEX IF NOT EXISTS employees_salary_id_idx
  ON employee_app.employees(salary_id);

CREATE INDEX IF NOT EXISTS employees_seating_id_idx
  ON employee_app.employees(seating_id);

CREATE INDEX IF NOT EXISTS employee_devices_employee_id_idx
  ON employee_app.employee_devices(employee_id);

CREATE INDEX IF NOT EXISTS employee_devices_site_id_idx
  ON employee_app.employee_devices(site_id);

INSERT INTO employee_app.schema_migrations (version, description)
VALUES ('001', 'Create employee application schema')
ON CONFLICT (version) DO NOTHING;

COMMIT;
